name: drqv2
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch==1.10
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - numpy
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - tensorboard
    - imageio
    - imageio-ffmpeg
    - hydra-core
    - hydra-submitit-launcher
    - pandas
    - ipdb
    - yapf
    - mujoco_py
    - sklearn
    - matplotlib
    - opencv-python
