name: drqv2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.1.3
  - setuptools=59.0.1
  - numpy
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - nvidia::cudatoolkit=11.1
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - imageio
    - tensorboard
    - imageio-ffmpeg
    - hydra-core
    - hydra-submitit-launcher
    - pandas
    - ipdb
    - yapf
    - mujoco_py
    - sklearn
    - matplotlib
    - opencv-python
